feat(RFC): 0003 code teams
tauri-apps/rfcs pull request #4
Opened 2020-09-13 00:45 UTC by jbolda

I think plenty of this is open to discussion, but this should present a good base to open from.

2020-09-14 14:57 UTC, AmrBinBashir commented
I really like this separation of concerns. Each team will have to focus on their part of the code only and they will make sure that their code is well-written and tested. This will help to better maintain the project as it grows.  ❤

2020-09-15 04:46 UTC, tensor-programming commented
Looks good to me. Given how busy I've been and everyone else has been, we need new blood and some kind of on boarding incentive to keep development moving steadily.

2020-09-17 23:59 UTC, nklayman requested changes
Looks good, I think I found a few grammar mistakes though :)

2020-09-17 23:59 UTC, nklayman commented on texts/0003-code-teams.md
> +To address the inflow and outflow of members, we will list all team members and "open positions". Each team should have 3+ members, 3 of which being the primary members. The primary members should ha
"reward" to ~~my~~ **be** earned

2020-09-17 23:59 UTC, nklayman commented on texts/0003-code-teams.md
> +Members may step back as an "alumnus" member. All roles operate in the open so this is doesn't reduce access in any manner. Rather the intent is to signal that the time is not available for them to g
the open so this ~~is~~ doesn't

Rather, the (add comma)

2020-09-17 23:59 UTC, nklayman commented on texts/0003-code-teams.md
> +This should allow us to bring in more people to help out. More eyes covering every corner soups help, and relieving some of the managerial duties from core should allow more attention to security.
every corner ~~soups help~~ **will result in more bugs being caught**

2020-09-18 03:22 UTC, jbolda commented
> Looks good, I think I found a few grammar mistakes though :)

Thanks, can you tell I typed this up on my phone? 😆

2020-09-19 17:18 UTC, nothingismagick commented on texts/0003-code-teams.md
> +To address the inflow and outflow of members, we will list all team members and "open positions". Each team should have 3+ members, 3 of which being the primary members. The primary members should ha
```suggestion
To address the inflow and outflow of members, we will list all team members and "open positions". Each team should have 3+ members, 3 of which being the primary members. The primary members should have the most expectation of responsibility. The primary members are not lifetime, static positions. There is an expectation that they change with some frequency and not be a "reward" to be earned.
```

2020-09-19 17:18 UTC, nothingismagick commented on texts/0003-code-teams.md
> +Members may step back as an "alumnus" member. All roles operate in the open so this is doesn't reduce access in any manner. Rather the intent is to signal that the time is not available for them to g
```suggestion
Members may step back as an "alumnus" member. All roles operate in the open so this is doesn't reduce access in any manner. Rather, the intent is to signal that the time is not available for them to give real attention to the project. A way that one could temporarily or permanently step back without any guilt.
```

2020-09-19 17:19 UTC, nothingismagick commented on texts/0003-code-teams.md
> +This should allow us to bring in more people to help out. More eyes covering every corner soups help, and relieving some of the managerial duties from core should allow more attention to security.
```suggestion
This should allow us to bring in more people to help out. More eyes covering every corner will result in more bugs being caught, and relieving some of the managerial duties from core should allow more attention to security.
```

2020-09-19 17:20 UTC, nklayman approved these changes

2020-09-19 17:21 UTC, merged